#!/usr/bin/env groovy
pipeline {
    agent none

    triggers {
        cron('0 12 * * *')
    }

    environment {
        projectName = 'ePP'
        trunkBranchName = 'master'
    }
    options {
        buildDiscarder logRotator(artifactNumToKeepStr: '2')
    }
    stages {

        stage('Compilação, testes unitários, package e deploy para o nexus') {
            agent {
                kubernetes {
                    yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: assinador-cms
spec:
  limits:
  - default:
      memory: 1536Mi
      cpu: 1
"""
                }
            }
            tools {
                maven 'Maven'
            }
            steps {
                script {
                    sh "mvn -s settings.xml -Pbuild:all -Dgit-commit-id-plugin.useGitNative=true -Dmaven.test.failure.ignore -Dsurefire.useFile=false --batch-mode -V -U -e clean verify"
                    sh "mvn -s settings.xml -Pbuild:all --batch-mode -V -U -e checkstyle:checkstyle pmd:pmd pmd:cpd"
                }
            }
            post {
                success {
                    junit testResults: '**/target/surefire-reports/TEST-*.xml'

                    recordIssues enabledForFailure: true, tools: [mavenConsole(), java(), javaDoc()]
                    recordIssues enabledForFailure: true, tool: checkStyle()
                    // recordIssues enabledForFailure: true, tool: spotBugs()
                    recordIssues enabledForFailure: true, tool: cpd(pattern: '**/target/cpd.xml')
                    recordIssues enabledForFailure: true, tool: pmdParser(pattern: '**/target/pmd.xml')
                    archiveArtifacts allowEmptyArchive: true, artifacts: 'epp/**/target/*.war', caseSensitive: false, defaultExcludes: false, fingerprint: true, onlyIfSuccessful: true
                    archiveArtifacts allowEmptyArchive: true, artifacts: 'epp/**/target/*liquibase*.tar.gz', caseSensitive: false, defaultExcludes: false, fingerprint: true, onlyIfSuccessful: true
                    deleteDir()
                }
                failure {
                    deleteDir()
                }
            }
        }

    }

}

