/*
 IBPM - Ferramenta de produtividade Java
 Copyright (c) 1986-2009 Infox Tecnologia da Informação Ltda.

 Este programa é software livre; você pode redistribuí-lo e/ou modificá-lo 
 sob os termos da GNU GENERAL PUBLIC LICENSE (GPL) conforme publicada pela 
 Free Software Foundation; versão 2 da Licença.
 Este programa é distribuído na expectativa de que seja útil, porém, SEM 
 NENHUMA GARANTIA; nem mesmo a garantia implícita de COMERCIABILIDADE OU 
 ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.
 
 Consulte a GNU GPL para mais detalhes.
 Você deve ter recebido uma cópia da GNU GPL junto com este programa; se não, 
 veja em http://www.gnu.org/licenses/   
*/
package br.com.infox.ibpm.entity;
// Generated 30/10/2008 07:40:27 by Hibernate Tools 3.2.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import javax.validation.constraints.NotNull;

import br.com.infox.access.entity.UsuarioLogin;
/**
 * BloqueioUsuario generated by hbm2java
 */
@Entity
@Table(name = "tb_bloqueio_usuario", schema="public")
public class BloqueioUsuario implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer idBloqueioUsuario;
	private UsuarioLogin usuario;
	private Date dataBloqueio;
	private Date dataPrevisaoDesbloqueio;
	private String motivoBloqueio;
	private Date dataDesbloqueio;

	public BloqueioUsuario() {
	}

	@SequenceGenerator(name = "generator", sequenceName = "public.sq_tb_bloqueio_usuario")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_bloqueio_usuario", unique = true, nullable = false)
	public Integer getIdBloqueioUsuario() {
		return this.idBloqueioUsuario;
	}

	public void setIdBloqueioUsuario(Integer idBloqueioUsuario) {
		this.idBloqueioUsuario = idBloqueioUsuario;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	@NotNull
	public UsuarioLogin getUsuario() {
		return this.usuario;
	}

	public void setUsuario(UsuarioLogin usuario) {
		this.usuario = usuario;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_bloqueio", nullable = false)
	@NotNull
	public Date getDataBloqueio() {
		return this.dataBloqueio;
	}

	public void setDataBloqueio(Date dataBloqueio) {
		this.dataBloqueio = dataBloqueio;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_previsao_desbloqueio", nullable = false)
	@NotNull
	public Date getDataPrevisaoDesbloqueio() {
		return this.dataPrevisaoDesbloqueio;
	}

	public void setDataPrevisaoDesbloqueio(Date dataPrevisaoDesbloqueio) {
		this.dataPrevisaoDesbloqueio = dataPrevisaoDesbloqueio;
	}

	@Column(name = "ds_motivo_bloqueio", nullable = false)
	@NotNull
	public String getMotivoBloqueio() {
		return this.motivoBloqueio;
	}

	public void setMotivoBloqueio(String motivoBloqueio) {
		this.motivoBloqueio = motivoBloqueio;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_desbloqueio")
	public Date getDataDesbloqueio() {
		return this.dataDesbloqueio;
	}

	public void setDataDesbloqueio(Date dataDesbloqueio) {
		this.dataDesbloqueio = dataDesbloqueio;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getIdBloqueioUsuario() == null) {
			return false;
		}
		if (!(obj instanceof BloqueioUsuario)) {
			return false;
		}
		BloqueioUsuario other = (BloqueioUsuario) obj;
		return getIdBloqueioUsuario().equals(other.getIdBloqueioUsuario());
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + getIdBloqueioUsuario();
		return result;
	}
}