/*
 IBPM - Ferramenta de produtividade Java
 Copyright (c) 1986-2009 Infox Tecnologia da Informação Ltda.

 Este programa é software livre; você pode redistribuí-lo e/ou modificá-lo 
 sob os termos da GNU GENERAL PUBLIC LICENSE (GPL) conforme publicada pela 
 Free Software Foundation; versão 2 da Licença.
 Este programa é distribuído na expectativa de que seja útil, porém, SEM 
 NENHUMA GARANTIA; nem mesmo a garantia implícita de COMERCIABILIDADE OU 
 ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.
 
 Consulte a GNU GPL para mais detalhes.
 Você deve ter recebido uma cópia da GNU GPL junto com este programa; se não, 
 veja em http://www.gnu.org/licenses/   
*/
package br.com.infox.ibpm.entity;
// Generated 30/10/2008 07:40:27 by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.validation.constraints.NotNull;
/**
 * ItemTipoDocumento generated by hbm2java
 */

@Entity
@Table(name = "tb_item_tipo_documento", schema="public")
public class ItemTipoDocumento implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int idItemTipoDocumento;
	private Localizacao localizacao;
	private GrupoModeloDocumento grupoModeloDocumento;

	public ItemTipoDocumento() {
	}

	@SequenceGenerator(name = "generator", sequenceName = "public.sq_tb_item_tipo_documento")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_item_tipo_documento", unique = true, nullable = false)
	public int getIdItemTipoDocumento() {
		return this.idItemTipoDocumento;
	}

	public void setIdItemTipoDocumento(int idItemTipoDocumento) {
		this.idItemTipoDocumento = idItemTipoDocumento;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_localizacao")
	public Localizacao getLocalizacao() {
		return this.localizacao;
	}

	public void setLocalizacao(Localizacao localizacao) {
		this.localizacao = localizacao;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo_modelo_documento", nullable = false)
	@NotNull
	public GrupoModeloDocumento getGrupoModeloDocumento() {
		return this.grupoModeloDocumento;
	}

	public void setGrupoModeloDocumento(
			GrupoModeloDocumento grupoModeloDocumento) {
		this.grupoModeloDocumento = grupoModeloDocumento;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof ItemTipoDocumento)) {
			return false;
		}
		ItemTipoDocumento other = (ItemTipoDocumento) obj;
		if (getIdItemTipoDocumento() != other.getIdItemTipoDocumento()) {
			return false;
		}
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + getIdItemTipoDocumento();
		return result;
	}
}