/*
 IBPM - Ferramenta de produtividade Java
 Copyright (c) 1986-2009 Infox Tecnologia da Informação Ltda.

 Este programa é software livre; você pode redistribuí-lo e/ou modificá-lo 
 sob os termos da GNU GENERAL PUBLIC LICENSE (GPL) conforme publicada pela 
 Free Software Foundation; versão 2 da Licença.
 Este programa é distribuído na expectativa de que seja útil, porém, SEM 
 NENHUMA GARANTIA; nem mesmo a garantia implícita de COMERCIABILIDADE OU 
 ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA.
 
 Consulte a GNU GPL para mais detalhes.
 Você deve ter recebido uma cópia da GNU GPL junto com este programa; se não, 
 veja em http://www.gnu.org/licenses/   
*/
package br.com.infox.ibpm.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import javax.validation.constraints.Size;
import javax.validation.constraints.NotNull;

/**
 * Variavel generated by hbm2java
 */
@Entity
@Table(name = "tb_jbpm_variavel_label", schema="public")
public class JbpmVariavelLabel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int idJbpmVariavelLabel;
	private String nomeVariavel;
	private String labelVariavel;

	public JbpmVariavelLabel() {
	}

	@SequenceGenerator(name = "generator", sequenceName = "public.sq_tb_jbpm_variavel_label")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_jbpm_variavel_label", unique = true, nullable = false)
	public int getIdJbpmVariavelLabel() {
		return this.idJbpmVariavelLabel;
	}

	public void setIdJbpmVariavelLabel(int idJbpmVariavelLabel) {
		this.idJbpmVariavelLabel = idJbpmVariavelLabel;
	}

	@Column(name = "nm_variavel", nullable = false, length = 100, unique = true)
	@NotNull
	@Size(max = 100)
	public String getNomeVariavel() {
		return this.nomeVariavel;
	}

	public void setNomeVariavel(String variavel) {
		this.nomeVariavel = variavel;
	}

	@Column(name = "ds_label_variavel", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getLabelVariavel() {
		return this.labelVariavel;
	}

	public void setLabelVariavel(String valorVariavel) {
		this.labelVariavel = valorVariavel;
	}

	@Override
	public String toString() {
		return nomeVariavel;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof JbpmVariavelLabel)) {
			return false;
		}
		JbpmVariavelLabel other = (JbpmVariavelLabel) obj;
		if (getIdJbpmVariavelLabel() != other.getIdJbpmVariavelLabel()) {
			return false;
		}
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + getIdJbpmVariavelLabel();
		return result;
	}
}